server:
  port: 8101

jwt:
  tokenHeader: Authorization
  secret: nbiot-management
  expiration: 604800
  tokenHead: Bearer

secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /webjars/springfox-swagger-ui/**
      - /**/v2/api-docs
      - /api/v1/nbiot/admin/login
      - /api/v1/nbiot/admin/register
      - /api/v1/nbiot/device/**
      - /druid/**
      - /actuator/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
spring:
  profiles:
    active: dev

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: gantch # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: nbiot/images/ # 上传文件夹路径前缀

logging:
  level:
    root: info
    com.gantch.nbiotmanagement: debug
#    file: nbiot_log.log