server:
  port: 8101

jwt:
  tokenHeader: Authorization
  secret: nbiot-management
  expiration: 604800 #Token的有效期为7天
  tokenHead: Bearer

secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /webjars/springfox-swagger-ui/**
      - /**/v2/api-docs
      - /api/v1/nbiot/management/admin/login
      - /api/v1/nbiot/management/admin/register
      - /api/v1/nbiot/management/device/**
      - /api/v1/nbiot/management/device/group/**
      - /api/v1/nbiot/device/nbwebsokcet
      - /druid/**
      - /actuator/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
spring:
  profiles:
    active: dev


file:
  base-path: D:\Gantch\userUpload\

logging:
  level:
    root: info
    com.gantch.nbiotmanagement: debug
#    file: nbiot_log.log